### ISSUE TITLE
Sync Comments into Discussions

### ISSUE THREAD

**Issue by n3wt0n** [danhellem/github-actions-issue-to-work-item#57]
Would be great if we can sync Issue comments into AzDO Boards Discussion.

Any thought about it?

[AB#5434](https://dev.azure.com/danhellem/56243fe6-2ed4-4398-acde-6a289bc1d89a/_workitems/edit/5434)

**Comment by danhellem** [comment]
@n3wt0n right now i believe it posts the comment when the comment starts in the Issue. Is that not the case for you?

**Comment by n3wt0n** [comment]
Hi @danhellem yes now it appears to work... Not sure why but when I've tried before it didn't create the comment in AzDO.

So I'd say this is working now :)

There is only a small formatting issue now, there is a new line too many:

![image](https://user-images.githubusercontent.com/13121206/96058537-10997680-0ebe-11eb-9c92-77e578dd0d5c.png)

**Comment by danhellem** [comment]
Cool...I will fix that formatting issue

**Comment by danhellem** [comment]
this looks like an issue with the ADO API. I am not setting any line breaks before the save

**Comment by maxisam** [comment]
It seems like it doesn't work now.

**Comment by danhellem** [comment]
@maxisam 

> It seems like it doesn't work now.

What does that mean? not getting any comments at all to show up in ADO?

**Comment by maxisam** [comment]
yeah, that is what happens to me. Does it work for you?

**Comment by danhellem** [comment]
@maxisam yes it works fine. I will double check it later this week though

**Comment by maxisam** [comment]
The action workflow never gets trigger for comment. 

Should I add something like issue_comment:  types: [created, edited]

**Comment by maxisam** [comment]
ok, it works with issue_comment trigger, should we update readme?

```
issue_comment: 
  types: [created, edited, deleted]
```

**Comment by danhellem** [comment]
The issue here is that comments by themselves fire a different web hook event. This action is currently only tracking the issue event, not the issue_comment event. So as long as you make a comment change with another change it will work. But if you do a comment change on it's own it won't work.

I will keep this open and update the code in a week or two to handle the issue_comment event

**Comment by danhellem** [comment]
Picking this back up and added to my to-do list to get done in the next couple of weeks

**Comment by danhellem** [comment]
Sorry for the delay. I changed teams and this has been a low priority. Trying to get it done in the next few weeks.

**Comment by danhellem** [comment]
Started looking it this as I have been working on other issues. the problem is that `issue_comment` is a separate event with a different payload. Creating isn't too bad. However, editing and updates back to the right work item comment is little bit harder.  

Do you think we need to worry about comment edits and reactions? Or just adding the comment but understanding it will get outdated as soon as a Issue is commented on?

I was thinking that we could just post a notification that a comment was added/edited with date-time stamp and post that in the work item comments with a link back to the issue. That way you know a comment was made and can go view it without worrying about keeping them synced.

Thoughts?

**Comment by maxisam** [comment]
I am good with your idea

**Comment by danhellem** [comment]
Linked to #114

**Comment by danhellem** [comment]
Testing web hook

**Comment by danhellem** [comment]
This is finally done. thanks for your help on this @hvpatil

**Comment by mangeshpatiln** [comment]
The issue is reflecting the same name all over in creation of issue as well as updated and commented. The name which it is tacking is the token owner name.
