### ISSUE TITLE
Syncing all actions in GitHub (such as PRs) 

### ISSUE THREAD

**Issue by RheaPatel** [danhellem/github-actions-issue-to-work-item#64]
This is a bug we are experiencing. 
Any action made on GitHub such as a PR - is getting recorded as a user story in Azure DevOps. 

[AB#709](https://dev.azure.com/privatepreview/5136ae2e-ad01-4fa4-b7e9-7550b8cdd2c3/_workitems/edit/709)

**Comment by danhellem** [comment]
You will need to check the settings in the workflow file. The default in the readme.md is setting it to "User Story". But you can create your own custom work item type and use that instead of User Stories. Example

![image](https://user-images.githubusercontent.com/10525048/103293754-53d79180-49a5-11eb-99ed-5e1a071f6650.png)

**Comment by RheaPatel** [comment]
So sorry the problem is that I don't want Pull Requests to be synced to ADO I only require issues to sync across
Are there any solutions for this? @danhellem

**Comment by danhellem** [comment]
@RheaPatel yes. This action does not sync PR's. My other extension does. Just follow the steps in the readme.md

And check to make sure the other action is not installed.

**Comment by mattzech** [comment]
Hi I am having the same issue. PR's are getting synced to Azure when I only want Issues to be synced

**Comment by mattzech** [comment]
Looking into it more, it seems like the "issue_comment" is getting triggered when a PR get commented on, which then creates an Issue in Azure of the PR since it cannot find an existing one. Is there a better way to get comments to sync?
